:issue 1:07-15-2020:06:52:closed

Traceback (most recent call last):
  File "/Users/charles/PycharmProjects/LWTest/LWTest/gui/main_window/main_window.py", line 234, in _upgrade_successful
    self.sensor_log.record_firmware_version(serial_number, lwt.LATEST_FIRMWARE_VERSION_NUMBER)
  File "/Users/charles/PycharmProjects/LWTest/LWTest/sensor.py", line 202, in record_firmware_version
    self.get_sensor_by_phase(phase).firmware_version = version
AttributeError: 'NoneType' object has no attribute 'firmware_version'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

:issue 2:07-22-2020:11:53:Open
Traceback (most recent call last):
  File "/Users/charles/PycharmProjects/LWTest/LWTest/gui/main_window/main_window.py", line 400, in _process_high_data_readings
    self.validator.validate_high_voltage_readings(data_set)
  File "/Users/charles/PycharmProjects/LWTest/LWTest/validate.py", line 53, in validate_high_voltage_readings
    self._validate_readings(_HIGH_MINS, _HIGH_MAXS, _HIGH_COLS, readings)
  File "/Users/charles/PycharmProjects/LWTest/LWTest/validate.py", line 76, in _validate_readings
    readings_as_floats = tuple([float(reading.replace(",", "")) for reading in sensor_readings])
  File "/Users/charles/PycharmProjects/LWTest/LWTest/validate.py", line 76, in <listcomp>
    readings_as_floats = tuple([float(reading.replace(",", "")) for reading in sensor_readings])
ValueError: could not convert string to float: 'NA'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)